// @license
// Copyright (c) 2019 - 2025 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:convert';
import 'dart:io';

// ignore: lines_longer_than_80_chars
import 'package:gg_local_package_dependencies/gg_local_package_dependencies.dart';
import 'package:gg_one/gg_one.dart' as gg;
import 'package:mocktail/mocktail.dart';
import 'package:path/path.dart' as path;
import 'package:pub_semver/pub_semver.dart';
import 'package:pubspec_parse/pubspec_parse.dart';

import 'package:gg_multi_core/src/backend/git_snapshot.dart';
import 'package:gg_multi_core/src/backend/process_runner.dart';

/// The outcome of [PublishSkipCheck.get] for one ticket repository.
class PublishSkipDecision {
  /// Constructor.
  const PublishSkipDecision({required this.skip, required this.reason});

  /// Whether publishing the repository can be skipped.
  final bool skip;

  /// Why the repository can be skipped ([skip] is true) or why it has to be
  /// published ([skip] is false).
  final String reason;
}

/// Decides whether a ticket repository needs to be published at all.
///
/// Many repositories are only part of a ticket because they sit between two
/// changed packages in the dependency chain. Such a pass-through repository
/// does not need a release when
///
/// 1. no dependency published earlier in the run received a version its
///    already-published constraint cannot absorb (i.e. no breaking bump —
///    for versions >= 1.0.0 that is a whole-number/major increase, for 0.x
///    versions the minor position acts as the breaking one), and
/// 2. the repository carries no manual changes — the working tree is clean
///    and every commit this ticket *contributes* was generated by gg itself.
///    Contributed means: not reachable from the main branch (work already
///    merged there is not a change of this ticket) and newer than the last
///    merge-back commit of an earlier release (gg squash-merges, so the
///    original feature commits never become ancestors of main and would
///    otherwise linger in the range forever).
///
/// Every situation that cannot be judged reliably (unknown dependency
/// version, unparsable constraint, missing git history, …) results in
/// »publish« — skipping is only ever chosen when it is provably safe.
class PublishSkipCheck {
  /// Constructor.
  PublishSkipCheck({ProcessRunner? processRunner})
    : _processRunner = processRunner ?? defaultProcessRunner;

  /// Runs the git commands used to inspect the repository history.
  final ProcessRunner _processRunner;

  /// Every commit message gg generates itself starts with this prefix.
  @Deprecated('Use ggCommitPrefix from package:gg_git/gg_git.dart')
  static const String ggCommitPrefix = gg.ggCommitPrefix;

  /// Commit subjects gg versions before the »#gg: « prefix created.
  @Deprecated('Use legacyGgCommitMessages from package:gg_git/gg_git.dart')
  static const Set<String> legacyGgCommitMessages = gg.legacyGgCommitMessages;

  /// The files gg's bookkeeping commits legitimately touch.
  ///
  /// Kept as the flat set it always was. The live check uses
  /// [gg.isGgOwnedPath], which additionally matches by basename, knows the
  /// `.gg` directory at any depth and recognizes the generated version
  /// files — use that instead of comparing against this set.
  @Deprecated('Use isGgOwnedPath from package:gg_one/gg_one.dart')
  static final Set<String> ggOwnedFiles = <String>{
    ...gg.ggOwnedFileNames,
    ...gg.ggOwnedRootFiles,
  };

  // ...........................................................................
  /// Returns the skip decision for [repo].
  ///
  /// [refVersions] maps the package names of the repositories processed
  /// earlier in this run to the version they now have (published repos carry
  /// their fresh version, skipped repos their unchanged one).
  Future<PublishSkipDecision> get({
    required Node repo,
    required Map<String, String> refVersions,
  }) async {
    final dependencyReason = _dependencyPublishReason(repo, refVersions);
    if (dependencyReason != null) {
      return PublishSkipDecision(skip: false, reason: dependencyReason);
    }

    final manualChangeReason = await _manualChangeReason(repo.directory);
    if (manualChangeReason != null) {
      return PublishSkipDecision(skip: false, reason: manualChangeReason);
    }

    return const PublishSkipDecision(
      skip: true,
      reason: 'Nothing changed. Skip publishing.',
    );
  }

  // ######################
  // Private
  // ######################

  // ...........................................................................
  /// Returns why a dependency forces a publish of [repo], or null when every
  /// dependency's new version is still covered by the constraint the
  /// repository publishes.
  String? _dependencyPublishReason(Node repo, Map<String, String> refVersions) {
    final regularDeps = _regularDependencyNames(repo.directory);
    final constraints = _declaredConstraints(repo.directory, regularDeps);

    for (final dep in repo.dependencies.values) {
      final names = <String>{dep.name, ...dep.aliases};
      final declaredNames = names.intersection(regularDeps);
      if (declaredNames.isEmpty) {
        // A dev-only dependency is invisible to consumers of the published
        // package, so its version never forces a release.
        continue;
      }

      final newVersionString = _newVersionOf(dep, refVersions);
      if (newVersionString == null) {
        return 'the version of dependency »${dep.name}« is unknown';
      }

      final Version newVersion;
      try {
        newVersion = Version.parse(newVersionString);
      } on FormatException {
        return 'the version »$newVersionString« of dependency '
            '»${dep.name}« is not a valid semver version';
      }

      for (final name in declaredNames) {
        final constraint = constraints[name];
        if (constraint == null) {
          return 'no version constraint for dependency »$name« '
              'could be determined';
        }
        if (!constraint.allows(newVersion)) {
          return 'dependency »$name« moved to $newVersion which is '
              'outside the published constraint »$constraint«';
        }
      }
    }

    return null;
  }

  // ...........................................................................
  /// Returns the new version of [dep] captured earlier in the run, looked up
  /// under any of its names (Dart name, npm name, directory name).
  String? _newVersionOf(Node dep, Map<String, String> refVersions) {
    for (final name in <String>{dep.name, ...dep.aliases}) {
      final version = refVersions[name];
      if (version != null) {
        return version;
      }
    }
    return null;
  }

  // ...........................................................................
  /// The names of the *regular* dependencies of the repo in [repoDir] —
  /// `dependencies` of pubspec.yaml plus `dependencies` of package.json.
  /// Dev dependencies are excluded on purpose: registries ignore them when
  /// resolving consumers of the published package.
  Set<String> _regularDependencyNames(Directory repoDir) {
    final result = <String>{};

    final pubspec = _parsedPubspec(repoDir);
    if (pubspec != null) {
      result.addAll(pubspec.dependencies.keys);
    }

    final packageJson = _parsedPackageJson(repoDir);
    final npmDeps = packageJson?['dependencies'];
    if (npmDeps is Map<String, dynamic>) {
      result.addAll(npmDeps.keys);
    }

    return result;
  }

  // ...........................................................................
  /// The version constraints [repoDir] publishes for [names].
  ///
  /// The specs backed up by gg_localize_refs are authoritative — they hold
  /// the original refs while the manifest may be localized to path/git refs.
  /// Names without a backup entry fall back to the constraint currently
  /// declared in the manifest. A null value means the constraint could not
  /// be determined.
  Map<String, VersionConstraint?> _declaredConstraints(
    Directory repoDir,
    Set<String> names,
  ) {
    final manifest = _manifestConstraints(repoDir);
    final saved = _savedDependencySpecs(repoDir);

    final result = <String, VersionConstraint?>{};
    for (final name in names) {
      if (saved.containsKey(name)) {
        result[name] = _constraintFromSpec(saved[name]);
      } else {
        result[name] = manifest[name];
      }
    }
    return result;
  }

  // ...........................................................................
  /// The version constraints currently declared in the manifests of
  /// [repoDir]. Localized refs (path/git) yield no entry.
  Map<String, VersionConstraint> _manifestConstraints(Directory repoDir) {
    final result = <String, VersionConstraint>{};

    final pubspec = _parsedPubspec(repoDir);
    if (pubspec != null) {
      for (final entry in pubspec.dependencies.entries) {
        final dependency = entry.value;
        if (dependency is HostedDependency) {
          result[entry.key] = dependency.version;
        }
      }
    }

    final packageJson = _parsedPackageJson(repoDir);
    final npmDeps = packageJson?['dependencies'];
    if (npmDeps is Map<String, dynamic>) {
      for (final entry in npmDeps.entries) {
        final constraint = _tryParseConstraint(entry.value?.toString());
        if (constraint != null) {
          result[entry.key] = constraint;
        }
      }
    }

    return result;
  }

  // ...........................................................................
  /// The original dependency specs gg_localize_refs backed up before
  /// localizing the refs of [repoDir].
  ///
  /// Dart writes `.gg/gg_localize_refs_backup_dart.json` and TypeScript
  /// `.gg/gg_localize_refs_backup_ts.json` today. The older spellings — one
  /// shared name inside `.gg`, its hidden predecessor, and the hidden file
  /// TypeScript kept in the repo root — are still read so checkouts made
  /// before the renames keep working. Reading only a legacy name made every
  /// git-localized repo look constraint-less, which forced a publish for
  /// repos that carry nothing but gg's own commits.
  Map<String, dynamic> _savedDependencySpecs(Directory repoDir) {
    final result = <String, dynamic>{};
    final files = [
      File(path.join(repoDir.path, '.gg_localize_refs_backup.json')),
      File(path.join(repoDir.path, '.gg', '.gg_localize_refs_backup.json')),
      File(path.join(repoDir.path, '.gg', 'gg_localize_refs_backup.json')),
      File(path.join(repoDir.path, '.gg', 'gg_localize_refs_backup_dart.json')),
      File(path.join(repoDir.path, '.gg', 'gg_localize_refs_backup_ts.json')),
    ];
    for (final file in files) {
      if (!file.existsSync()) {
        continue;
      }
      try {
        final decoded = jsonDecode(file.readAsStringSync());
        if (decoded is Map<String, dynamic>) {
          result.addAll(decoded);
        }
      } catch (_) {
        // An unreadable backup contributes nothing; affected dependencies
        // stay undetermined which makes the decision fall back to publish.
      }
    }
    return result;
  }

  // ...........................................................................
  /// Extracts the version constraint from a backed-up dependency [spec] —
  /// either a plain string (`^1.2.3`) or a map carrying a `version` key
  /// (git dependencies). Returns null when there is none or it is unparsable.
  VersionConstraint? _constraintFromSpec(dynamic spec) {
    if (spec is String) {
      return _tryParseConstraint(spec);
    }
    if (spec is Map) {
      final version = spec['version'];
      if (version != null) {
        return _tryParseConstraint(version.toString());
      }
    }
    return null;
  }

  // ...........................................................................
  /// Parses [raw] as version constraint, returning null when it is not one.
  VersionConstraint? _tryParseConstraint(String? raw) {
    if (raw == null || raw.trim().isEmpty) {
      return null;
    }
    try {
      return VersionConstraint.parse(raw.trim());
    } on FormatException {
      return null;
    }
  }

  // ...........................................................................
  /// The parsed pubspec.yaml of [repoDir], or null when absent/unparsable.
  Pubspec? _parsedPubspec(Directory repoDir) {
    final file = File(path.join(repoDir.path, 'pubspec.yaml'));
    if (!file.existsSync()) {
      return null;
    }
    try {
      return Pubspec.parse(file.readAsStringSync());
    } catch (_) {
      return null;
    }
  }

  // ...........................................................................
  /// The parsed package.json of [repoDir], or null when absent/unparsable.
  Map<String, dynamic>? _parsedPackageJson(Directory repoDir) {
    final file = File(path.join(repoDir.path, 'package.json'));
    if (!file.existsSync()) {
      return null;
    }
    try {
      final decoded = jsonDecode(file.readAsStringSync());
      return decoded is Map<String, dynamic> ? decoded : null;
    } catch (_) {
      return null;
    }
  }

  // ...........................................................................
  /// Returns why [repoDir] contains manual changes, or null when everything
  /// on top of the last release ([_compareBase]) was generated by gg.
  Future<String?> _manualChangeReason(Directory repoDir) async {
    try {
      final status = await _runGit(<String>[
        'status',
        '--porcelain',
      ], repoDir: repoDir);
      // A tree dirty in nothing but lock files carries no manual work: a
      // `pub get` — the Dart VS Code extension fires one whenever a manifest
      // is written — rewrites them behind everybody's back. Treating that as
      // a manual change would publish a repo nobody touched.
      if (status.isNotEmpty && !gg.isLockFileOnlyDrift(status)) {
        return 'the working tree has uncommitted changes';
      }

      final mainRef = await _mainRef(repoDir);
      if (mainRef == null) {
        return 'no main branch to compare against was found';
      }

      // Everything reachable from the main branch is already on it, and
      // everything up to the last merge-back is already released — what is
      // left is exactly what this ticket contributes.
      final anchor = await _lastMergeBackCommit(repoDir);
      final commits = await _runGit(<String>[
        'log',
        '--no-merges',
        '--format=%H%x09%s',
        'HEAD',
        '--not',
        mainRef,
        ?anchor,
      ], repoDir: repoDir);

      for (final line in commits.split('\n')) {
        final entry = line.trim();
        if (entry.isEmpty) {
          continue;
        }
        final tab = entry.indexOf('\t');
        final hash = tab < 0 ? entry : entry.substring(0, tab);
        final subject = tab < 0 ? '' : entry.substring(tab + 1).trim();

        if (!_isGgGenerated(subject)) {
          return 'the repo contains the manual commit »$subject«';
        }

        // gg's ref commits are force commits — they sweep pending user
        // edits into the bookkeeping commit. A gg-labeled commit touching
        // a non-gg file therefore carries user work and blocks the skip.
        final swallowedFile = await _firstNonGgFile(hash, repoDir);
        if (swallowedFile != null) {
          return 'the gg commit »$subject« also changes »$swallowedFile«';
        }
      }

      return null;
    } catch (e) {
      // A history that cannot be inspected cannot prove the repo unchanged.
      return 'the git history could not be inspected ($e)';
    }
  }

  // ...........................................................................
  /// Whether [subject] is a commit message gg generated itself.
  ///
  /// One shared predicate with the producers in gg_git, so what gg writes and
  /// what this check accepts cannot drift apart.
  bool _isGgGenerated(String subject) => gg.isGgGenerated(subject);

  // ...........................................................................
  /// Returns the first file of commit [hash] that is not one gg's
  /// bookkeeping legitimately touches, or null when the commit only
  /// contains gg-owned files.
  Future<String?> _firstNonGgFile(String hash, Directory repoDir) async {
    final files = await _runGit(<String>[
      'show',
      '--name-only',
      '--format=',
      hash,
    ], repoDir: repoDir);
    for (final line in files.split('\n')) {
      final file = line.trim();
      if (file.isEmpty || _isGgOwnedPath(file)) {
        continue;
      }
      return file;
    }
    return null;
  }

  // ...........................................................................
  /// Whether [filePath] (repo-relative, forward slashes as printed by git)
  /// belongs to gg's own bookkeeping files.
  ///
  /// The same predicate the system-commit helper uses when it decides what a
  /// »#gg: « commit may contain — read side and write side share one source.
  bool _isGgOwnedPath(String filePath) => gg.isGgOwnedPath(filePath);

  // ...........................................................................
  /// The main branch the repository is compared against.
  ///
  /// `origin/<main>` first — it is what everybody else sees — with the local
  /// branch as fallback for a repository whose remote is unreachable. Null
  /// when neither exists, which counts as undecidable and therefore
  /// publishes.
  Future<String?> _mainRef(Directory repoDir) async {
    const candidates = ['origin/main', 'origin/master', 'main', 'master'];
    for (final candidate in candidates) {
      final sha = await _runGit(
        <String>['rev-parse', '--verify', '--quiet', candidate],
        repoDir: repoDir,
        allowFailure: true,
      );
      if (sha.isNotEmpty) {
        return candidate;
      }
    }
    return null;
  }

  /// The last commit that folded a released main branch back into this
  /// feature branch, or null when the branch never carried a release.
  ///
  /// gg merges the feature branch into main by **squash**, so the original
  /// feature commits never become ancestors of main. Without this anchor they
  /// stay in the comparison range forever and a ticket that was published
  /// once would look changed on every later run. The merge-back commit
  /// `do publish` writes right after a release marks the point up to which
  /// everything is released; only what follows it belongs to this ticket.
  ///
  /// Matched by the shared [gg.ggMergeBackPrefix], so producer and reader
  /// cannot drift apart.
  Future<String?> _lastMergeBackCommit(Directory repoDir) async {
    final hash = await _runGit(
      <String>[
        'log',
        '-1',
        '--format=%H',
        // A fixed string, not a pattern — the prefix carries no regex meta
        // characters today, and --fixed-strings keeps it that way.
        '--fixed-strings',
        '--grep=${gg.ggMergeBackPrefix}',
        'HEAD',
      ],
      repoDir: repoDir,
      allowFailure: true,
    );
    return hash.isEmpty ? null : hash;
  }

  // ...........................................................................
  /// Runs git with [args] in [repoDir] and returns the trimmed stdout.
  Future<String> _runGit(
    List<String> args, {
    required Directory repoDir,
    bool allowFailure = false,
  }) => runGit(
    _processRunner,
    args,
    repoDir: repoDir,
    allowFailure: allowFailure,
  );
}

/// Mock for [PublishSkipCheck]
class MockPublishSkipCheck extends Mock implements PublishSkipCheck {}
